version: '3.1'

services:

  mysql-dev:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blogapp
    ports:
      - "3308:3306"
    volumes:
      - "./mysql/my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "./mysql/data:/var/lib/mysql:rw"

  # mysql-legacy:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: legacyapp
  #   ports:
  #     - "3309:3306"
  #
  pgdb:
    image: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER #root
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB #blogapp
    ports:
      - "5433:5432"
    volumes:
      - "./pgsql/postgresql.conf:/etc/postgresql/postgresql.conf"
      - "./pgsql/data:/var/lib/postgresql/data"
  admin:
    image: adminer
    ports:
      - 8080:8080

  # client:
  #   image: mysql:8.0.2
  #   depends_on:
  #     - mysql-dev
  #   command: mysql -uroot -ppassword -hmysql-dev blogapp
